server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///clouddb?serverTimezone=UTC


#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)


mybatis:
  #  config-location: classpath:mybaits/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: qqai.cloud.entity

eureka:
  client:
    #   表示自己需要注册到eureka server中  默认也是true
    register-with-eureka: true
    #   表示是否从eureka server中抓取已有的注册信息，默认为true，单节点无所谓，集群必须是设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true