server:
  port: 7001

eureka:
  instance:
    #    eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    #    表示不想注册中心注册自己
    register-with-eureka: false
    #    表明自己就是注册中心，职责就是误会服务实例，不需要去检索服务
    fetch-registry: false
    #    设置eureka server监护地址查询服务和注册读物都要依赖这个地址
    service-url:
      #      集群化服务器
#      defaultZone: http://eureka7002.com:7002/eureka
      #      单节点服务器
      defaultZone: http://eureka7001.com:7001/eureka